name: Terraform PR Plan

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]           # Runs on new PR, code push, PR reopen

jobs:
  terraform:
    runs-on: ubuntu-latest             # Uses Ubuntu VM as runner VM
    permissions:
      contents: read      # Read access to repo contents
      id-token: write     # Allows OIDC token creation for AWS
    steps:
      - name: Checkout    # Downloads your repo to the runner VM.
        uses: actions/checkout@v4

      - name: Setup Terraform                 #Installs Terraform 1.5.0 on the runner.
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Show runner path (debug)      # debug step to show working directory
        run: |
          echo "Working dir: $(pwd)"
          ls -la

      - name: Fetch Terraform vars
        uses: aws-actions/aws-secretsmanager-get-secret@v1
        id: secret
        with:
          secret-id: ${{ secrets.AWS_TF_VARS_SECRET_ARN }}
          json: true

      - name: Write Terraform vars
        run: |
          mkdir -p ./terraform
          echo "${{ steps.secret.outputs.secret }}" > ./terraform/terraform.tfvars.json

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: |
          terraform plan -out=tfplan.binary
          terraform show -no-color tfplan.binary > tfplan.txt

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan.txt
